<a href="https://colab.research.google.com/github/arturbernardo/eleicoes_fingerprint/blob/main/fingerprint_1994.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from google.colab import drive
from pathlib import Path
import os
import numpy as np
import matplotlib.pyplot as plt
import math
from matplotlib.colors import LogNorm
pd.options.display.max_columns = None

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive

In [22]:
st = pd.read_csv('/content/drive/MyDrive/data/eleicoes1994/votacao_secao_1994_BR.csv', encoding="ISO-8859-1", sep = ';',
                  dtype={
                          "SG_UF": pd.CategoricalDtype(),
                          "CD_MUNICIPIO": pd.Int64Dtype(),
                          "NR_LOCAL_VOTACAO": pd.Int64Dtype(),
                          "NR_ZONA": pd.Int64Dtype(),
                          "NR_SECAO": pd.CategoricalDtype()
                      })

st

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,36,CARLOS ANTONIO GOMES,1,-3,10000010100036,#NE,#NE
1,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,56,ENEAS FERREIRA CARNEIRO,25,-3,10000010100056,#NE,#NE
2,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,11,ESPERIDIAO AMIN HELOU FILHO,1,-3,10000010100011,#NE,#NE
3,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE
4,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,20,HERNANI GOULART FORTUNA,1,-3,10000010100020,#NE,#NE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401803,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,TO,BR,BRASIL,73318,ARAGUANA,34,40,1,PRESIDENTE,20,HERNANI GOULART FORTUNA,1,-3,27000270100020,#NE,#NE
1401804,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,TO,BR,BRASIL,73318,ARAGUANA,34,40,1,PRESIDENTE,13,LUIZ INACIO LULA DA SILVA,14,-3,27000270100013,#NE,#NE
1401805,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,TO,BR,BRASIL,73318,ARAGUANA,34,40,1,PRESIDENTE,15,ORESTES QUERCIA,1,-3,27000270100015,#NE,#NE
1401806,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,TO,BR,BRASIL,73318,ARAGUANA,34,40,1,PRESIDENTE,95,VOTO BRANCO,7,-3,-1,#NE,#NE
1401807,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,TO,BR,BRASIL,73318,ARAGUANA,34,40,1,PRESIDENTE,96,VOTO NULO,11,-3,-1,#NE,#NE

In [55]:
df_votos = st[st['SG_UF'] == 'AC']
df_votos

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,36,CARLOS ANTONIO GOMES,1,-3,10000010100036,#NE,#NE
1,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,56,ENEAS FERREIRA CARNEIRO,25,-3,10000010100056,#NE,#NE
2,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,11,ESPERIDIAO AMIN HELOU FILHO,1,-3,10000010100011,#NE,#NE
3,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE
4,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,20,HERNANI GOULART FORTUNA,1,-3,10000010100020,#NE,#NE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7539,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,20,HERNANI GOULART FORTUNA,1,-3,10000010100020,#NE,#NE
7540,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,13,LUIZ INACIO LULA DA SILVA,53,-3,10000010100013,#NE,#NE
7541,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,15,ORESTES QUERCIA,6,-3,10000010100015,#NE,#NE
7542,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,95,VOTO BRANCO,18,-3,-1,#NE,#NE
7543,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,96,VOTO NULO,5,-3,-1,#NE,#NE

In [62]:
df_det_rs = pd.read_csv('/content/drive/MyDrive/data/eleicoes1994/detalhe_votacao_secao_1994/detalhe_votacao_secao_1994_BRASIL.csv', encoding="ISO-8859-1", sep = ';',
                  dtype={
                          "SG_UF": pd.CategoricalDtype(),
                          "CD_MUNICIPIO": pd.Int64Dtype(),
                          "NR_LOCAL_VOTACAO": pd.Int64Dtype(),
                          "NR_ZONA": pd.Int64Dtype(),
                          "NR_SECAO": pd.CategoricalDtype()
                      })
df_det_rs

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,CD_CARGO,DS_CARGO,QT_APTOS,QT_COMPARECIMENTO,QT_ABSTENCOES,QT_VOTOS_NOMINAIS,QT_VOTOS_BRANCOS,QT_VOTOS_NULOS,QT_VOTOS_LEGENDA,QT_VOTOS_ANULADOS_APU_SEP,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1120,ACRELANDIA,8,8,1,PRESIDENTE,332,222,110,161,40,21,0,0,-3,#NE,#NE
1,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1120,ACRELANDIA,8,8,3,GOVERNADOR,332,222,110,145,71,6,0,0,-3,#NE,#NE
2,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1120,ACRELANDIA,8,8,5,SENADOR,332,222,110,286,128,30,0,0,-3,#NE,#NE
3,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1120,ACRELANDIA,8,8,7,DEPUTADO FEDERAL,332,222,110,114,55,35,18,0,-3,#NE,#NE
4,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1120,ACRELANDIA,8,8,8,DEPUTADO ESTADUAL,332,222,110,160,30,27,5,0,-3,#NE,#NE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938158,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,SP,SP,SAO PAULO,72451,VOTUPORANGA,147,99,3,GOVERNADOR,481,398,83,349,2,47,0,0,-3,#NE,#NE
938159,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,SP,SP,SAO PAULO,72451,VOTUPORANGA,147,100,3,GOVERNADOR,539,452,87,387,9,56,0,0,-3,#NE,#NE
938160,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,SP,SP,SAO PAULO,61921,ZACARIAS,214,21,3,GOVERNADOR,426,318,108,288,3,27,0,0,-3,#NE,#NE
938161,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,SP,SP,SAO PAULO,61921,ZACARIAS,214,22,3,GOVERNADOR,448,372,76,342,4,26,0,0,-3,#NE,#NE
938162,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,SP,SP,SAO PAULO,61921,ZACARIAS,214,36,3,GOVERNADOR,498,366,132,318,9,39,0,0,-3,#NE,#NE

In [63]:
df_rs_president = df_votos[df_votos['DS_CARGO'] == 'PRESIDENTE']
df_rs_president = df_rs_president[df_rs_president['NR_VOTAVEL'] == 45]
merged = df_rs_president.merge(df_det_rs, on=['SG_UF', 'CD_MUNICIPIO', 'NR_ZONA', 'NR_SECAO'])
merged

,DT_GERACAO_x,HH_GERACAO_x,ANO_ELEICAO_x,CD_TIPO_ELEICAO_x,NM_TIPO_ELEICAO_x,NR_TURNO_x,CD_ELEICAO_x,DS_ELEICAO_x,DT_ELEICAO_x,TP_ABRANGENCIA_x,SG_UF,SG_UE_x,NM_UE_x,CD_MUNICIPIO,NM_MUNICIPIO_x,NR_ZONA,NR_SECAO,CD_CARGO_x,DS_CARGO_x,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO_x,SQ_CANDIDATO,NM_LOCAL_VOTACAO_x,DS_LOCAL_VOTACAO_ENDERECO_x,DT_GERACAO_y,HH_GERACAO_y,ANO_ELEICAO_y,CD_TIPO_ELEICAO_y,NM_TIPO_ELEICAO_y,NR_TURNO_y,CD_ELEICAO_y,DS_ELEICAO_y,DT_ELEICAO_y,TP_ABRANGENCIA_y,SG_UE_y,NM_UE_y,NM_MUNICIPIO_y,CD_CARGO_y,DS_CARGO_y,QT_APTOS,QT_COMPARECIMENTO,QT_ABSTENCOES,QT_VOTOS_NOMINAIS,QT_VOTOS_BRANCOS,QT_VOTOS_NULOS,QT_VOTOS_LEGENDA,QT_VOTOS_ANULADOS_APU_SEP,NR_LOCAL_VOTACAO_y,NM_LOCAL_VOTACAO_y,DS_LOCAL_VOTACAO_ENDERECO_y
0,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,BR,BRASIL,RIO BRANCO,1,PRESIDENTE,357,268,89,245,13,10,0,0,-3,#NE,#NE
1,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,RIO BRANCO,3,GOVERNADOR,357,268,89,238,23,7,0,0,-3,#NE,#NE
2,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,RIO BRANCO,5,SENADOR,357,268,89,427,81,28,0,0,-3,#NE,#NE
3,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,RIO BRANCO,7,DEPUTADO FEDERAL,357,268,89,203,27,34,4,0,-3,#NE,#NE
4,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,RIO BRANCO,8,DEPUTADO ESTADUAL,357,268,89,233,15,19,1,0,-3,#NE,#NE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,55,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,SENADOR GUIOMARD,3,GOVERNADOR,150,141,9,118,18,5,0,0,-3,#NE,#NE
4976,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,55,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,SENADOR GUIOMARD,5,SENADOR,150,141,9,191,76,15,0,0,-3,#NE,#NE
4977,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,55,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,SENADOR GUIOMARD,7,DEPUTADO FEDERAL,150,141,9,97,19,25,0,0,-3,#NE,#NE
4978,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,55,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,ACRE,SENADOR GUIOMARD,8,DEPUTADO ESTADUAL,150,141,9,114,13,14,0,0,-3,#NE,#NE
4979,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,55,-3,10000010100045,#NE,#NE,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,AC,ACRE,SENADOR GUIOMARD,3,GOVERNADOR,150,135,15,125,1,9,0,0,-3,#NE,#NE

In [61]:
x = df_det_rs[df_det_rs['CD_MUNICIPIO'] == 1392]
x

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,CD_CARGO,DS_CARGO,QT_APTOS,QT_COMPARECIMENTO,QT_ABSTENCOES,QT_VOTOS_NOMINAIS,QT_VOTOS_BRANCOS,QT_VOTOS_NULOS,QT_VOTOS_LEGENDA,QT_VOTOS_ANULADOS_APU_SEP,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
1735,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,357,268,89,245,13,10,0,0,-3,#NE,#NE
1736,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,1,3,GOVERNADOR,357,268,89,238,23,7,0,0,-3,#NE,#NE
1737,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,1,5,SENADOR,357,268,89,427,81,28,0,0,-3,#NE,#NE
1738,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,1,7,DEPUTADO FEDERAL,357,268,89,203,27,34,4,0,-3,#NE,#NE
1739,24/11/2022,15:32:38,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,1,8,DEPUTADO ESTADUAL,357,268,89,233,15,19,1,0,-3,#NE,#NE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804339,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,398,3,GOVERNADOR,56,55,1,54,0,1,0,0,-3,#NE,#NE
804340,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,399,3,GOVERNADOR,155,132,23,127,0,5,0,0,-3,#NE,#NE
804341,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,401,3,GOVERNADOR,61,50,11,48,0,2,0,0,-3,#NE,#NE
804342,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,403,3,GOVERNADOR,66,61,5,56,0,5,0,0,-3,#NE,#NE
804343,24/11/2022,15:32:38,1994,2,Eleição Ordinária,2,1994002,Eleições Ordinárias - 1994,15/11/1994,F,AC,AC,ACRE,1392,RIO BRANCO,1,406,3,GOVERNADOR,56,52,4,49,0,3,0,0,-3,#NE,#NE

In [58]:
df_rs_president

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
3,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,1,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,137,-3,10000010100045,#NE,#NE
12,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,2,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,158,-3,10000010100045,#NE,#NE
21,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,3,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,160,-3,10000010100045,#NE,#NE
30,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,4,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,128,-3,10000010100045,#NE,#NE
39,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1392,RIO BRANCO,1,5,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,120,-3,10000010100045,#NE,#NE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7506,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1120,ACRELANDIA,8,94,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,85,-3,10000010100045,#NE,#NE
7513,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1120,ACRELANDIA,8,95,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,106,-3,10000010100045,#NE,#NE
7521,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1511,PLACIDO DE CASTRO,8,96,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,37,-3,10000010100045,#NE,#NE
7530,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,97,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,35,-3,10000010100045,#NE,#NE
7538,24/11/2022,08:52:41,1994,2,Eleição Ordinária,1,1994001,Eleições Ordinárias - 1994,03/10/1994,F,AC,BR,BRASIL,1538,SENADOR GUIOMARD,8,98,1,PRESIDENTE,45,FERNANDO HENRIQUE CARDOSO,55,-3,10000010100045,#NE,#NE